<?php
/**
 * IEMA CRMOps — AI Drafts Review Queue
 * -----------------------------------------------------------------------
 * Every draft here was generated by cron/generate-followup-drafts.php and
 * starts as 'pending_review'. Nothing leaves this queue without a human
 * clicking Approve — this page is the human-in-the-loop gate the AI spec
 * requires. "Approve & Send" attempts server-side mail() (unreliable on
 * many hosts) AND always shows a mailto: fallback so approval never
 * dead-ends.
 * -----------------------------------------------------------------------
 */
require_once __DIR__ . '/config.php';
require_login();

$role = current_role();
$uid = (int) ($_SESSION['user_id'] ?? 0);
$userName = $_SESSION['user_name'] ?? 'BD Team';
$error = '';
$success = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $draftId = (int) ($_POST['draft_id'] ?? 0);
    $action = $_POST['action'] ?? '';

    $draftStmt = $pdo->prepare('SELECT d.*, l.company_name, COALESCE(c.primary_contact_email, l.contact_email) AS contact_email, l.assigned_to FROM scheduled_email_drafts d JOIN leads l ON l.id = d.lead_id LEFT JOIN clients c ON c.id = l.client_id WHERE d.id = ?');
    $draftStmt->execute([$draftId]);
    $draft = $draftStmt->fetch();

    $canManage = $draft && ($role !== 'bd_officer' || (int) $draft['assigned_to'] === $uid);

    if (!$draft || !$canManage) {
        $error = 'Draft not found or you do not have permission to manage it.';
    } elseif ($action === 'dismiss') {
        $pdo->prepare("UPDATE scheduled_email_drafts SET status = 'dismissed', reviewed_by = ?, reviewed_at = NOW() WHERE id = ?")->execute([$uid, $draftId]);
        $success = 'Draft dismissed.';
    } elseif ($action === 'approve_send') {
        $editedSubject = trim($_POST['subject'] ?? $draft['subject']);
        $editedBody = trim($_POST['body'] ?? $draft['body']);

        $pdo->prepare("UPDATE scheduled_email_drafts SET subject = ?, body = ?, status = 'approved', reviewed_by = ?, reviewed_at = NOW() WHERE id = ?")
            ->execute([$editedSubject, $editedBody, $uid, $draftId]);

        if (!empty($draft['contact_email'])) {
            $sent = attempt_send_email($draft['contact_email'], $editedSubject, $editedBody, $userName, $_SESSION['user_email'] ?? 'noreply@iema-standards.com');
            if ($sent) {
                $pdo->prepare("UPDATE scheduled_email_drafts SET status = 'sent', sent_at = NOW() WHERE id = ?")->execute([$draftId]);
                $success = 'Approved and sent to ' . e($draft['contact_email']) . '.';
            } else {
                $success = 'Approved. Automatic sending isn\'t working on this server — use the "Open in Email App" link below to send it yourself.';
            }
        } else {
            $success = 'Approved. This lead has no contact email on file — add one on the lead record, or use the copy button to send manually.';
        }

        $audit = $pdo->prepare('INSERT INTO audit_log (user_id, action, entity_type, entity_id, details) VALUES (?,?,?,?,?)');
        $audit->execute([$uid, 'update', 'scheduled_email_draft', $draftId, 'Approved follow-up draft']);
    }
}

$scopeSql = $role === 'bd_officer' ? 'AND l.assigned_to = ?' : '';
$scopeParams = $role === 'bd_officer' ? [$uid] : [];

$stmt = $pdo->prepare("
    SELECT d.*, l.company_name, COALESCE(c.primary_contact_email, l.contact_email) AS contact_email, l.stage, u.name AS officer_name
    FROM scheduled_email_drafts d
    JOIN leads l ON l.id = d.lead_id
    LEFT JOIN clients c ON c.id = l.client_id
    LEFT JOIN users u ON u.id = l.assigned_to
    WHERE d.status = 'pending_review' $scopeSql
    ORDER BY d.created_at ASC
");
$stmt->execute($scopeParams);
$pendingDrafts = $stmt->fetchAll();

$historyStmt = $pdo->prepare("
    SELECT d.*, l.company_name
    FROM scheduled_email_drafts d
    JOIN leads l ON l.id = d.lead_id
    WHERE d.status IN ('sent','dismissed') $scopeSql
    ORDER BY d.reviewed_at DESC LIMIT 10
");
$historyStmt->execute($scopeParams);
$history = $historyStmt->fetchAll();

require_once __DIR__ . '/includes/header.php';
?>

<?php
// Summary numbers — from the pending queue and recent history already loaded.
$adSent      = count(array_filter($history, fn($h) => $h['status'] === 'sent'));
$adDismissed = count($history) - $adSent;
$adNoEmail   = count(array_filter($pendingDrafts, fn($d) => empty($d['contact_email'])));
$adOldest    = $pendingDrafts[0]['created_at'] ?? null;
$adOldestDays = $adOldest ? (int) floor((time() - strtotime($adOldest)) / 86400) : null;
?>
<style>
.ad-kpi { display:flex; align-items:flex-start; justify-content:space-between; gap:10px; }
.ad-stack { display:flex; flex-direction:column; gap:var(--gap); min-width:0; }
.ad-draft .tile-head { align-items:flex-start; }
.ad-company { font-family:'Libre Franklin',sans-serif; font-size:15.5px; font-weight:700; color:var(--ink-900); }
.ad-meta { font-size:12px; color:var(--ink-500); margin-top:3px; display:flex; gap:6px; flex-wrap:wrap; align-items:center; }
.ad-meta .icon { width:13px; height:13px; }
.ad-draft .form-field + .form-field { margin-top:12px; }
.ad-draft textarea { min-height:196px; line-height:1.6; }
@media (min-width:1025px){ .ad-side { position:sticky; top:88px; align-self:start; } }
.ad-warn { display:flex; gap:8px; align-items:flex-start; font-size:12px; color:#93690C; background:var(--amber-50); border:1px solid #F5DDA0; border-radius:10px; padding:9px 11px; margin-top:10px; }
.ad-warn .icon { width:15px; height:15px; flex-shrink:0; margin-top:1px; }
.ad-foot { display:flex; justify-content:space-between; align-items:center; gap:10px; flex-wrap:wrap; margin-top:16px; padding-top:14px; border-top:1px solid var(--line); }
.ad-foot .right { display:flex; gap:8px; flex-wrap:wrap; }
.ad-hist { display:flex; gap:10px; align-items:flex-start; padding:11px 0; border-bottom:1px solid var(--line-soft); }
.ad-hist:last-child { border-bottom:none; padding-bottom:0; }
.ad-hist:first-child { padding-top:0; }
.ad-hist .t { font-size:12.5px; color:var(--ink-700); line-height:1.45; min-width:0; }
.ad-hist .t b { color:var(--ink-900); font-weight:600; display:block; }
.ad-hist .d { font-size:11px; color:var(--ink-500); margin-top:2px; }
.ad-steps { list-style:none; display:flex; flex-direction:column; gap:12px; }
.ad-steps li { display:flex; gap:10px; font-size:12.5px; color:var(--ink-700); line-height:1.5; }
.ad-steps .n { width:22px; height:22px; border-radius:7px; background:#EEF2F8; color:var(--navy-700); font-size:11px; font-weight:800; display:flex; align-items:center; justify-content:center; flex-shrink:0; }
@media (max-width:760px){
  .bento > .ad-half { grid-column:span 6 !important; }
  .bento > .ad-half.tile { padding:14px; }
  .ad-half .tile-value { font-size:24px; }
  .ad-foot .right, .ad-foot .right > * { width:100%; }
}
</style>

<div class="page-head">
  <div>
    <div class="eyebrow">Human-in-the-loop</div>
    <h1>AI Drafts <?php if (count($pendingDrafts) > 0): ?><span class="badge red" style="vertical-align:4px;"><?php echo count($pendingDrafts); ?> awaiting review</span><?php endif; ?></h1>
    <p>Follow-up emails the AI drafted on schedule for stale leads. Nothing sends until you approve it.</p>
  </div>
</div>

<?php if ($error): ?><div class="alert error"><?php echo icon('alert'); ?><span><?php echo e($error); ?></span></div><?php endif; ?>
<?php if ($success): ?><div class="alert success"><?php echo icon('check'); ?><span><?php echo $success; ?></span></div><?php endif; ?>

<div class="bento">
  <section class="tile tile--navy span-4">
    <div class="ad-kpi">
      <div class="tile-label">Awaiting review</div>
      <div class="tile-icon"><?php echo icon('mail'); ?></div>
    </div>
    <div class="tile-value"><?php echo count($pendingDrafts); ?></div>
    <div class="tile-sub">
      <?php if ($adOldestDays !== null): ?>Oldest queued <?php echo $adOldestDays === 0 ? 'today' : $adOldestDays . ' day' . ($adOldestDays === 1 ? '' : 's') . ' ago'; ?><?php echo $adNoEmail ? ' · ' . $adNoEmail . ' missing an email' : ''; ?><?php else: ?>Queue is clear<?php endif; ?>
    </div>
  </section>
  <section class="tile span-4 ad-half">
    <div class="ad-kpi">
      <div class="tile-label">Sent</div>
      <div class="tile-icon green"><?php echo icon('send'); ?></div>
    </div>
    <div class="tile-value"><?php echo $adSent; ?></div>
    <div class="tile-sub">Of the last <?php echo count($history); ?> reviewed</div>
  </section>
  <section class="tile span-4 ad-half">
    <div class="ad-kpi">
      <div class="tile-label">Dismissed</div>
      <div class="tile-icon navy"><?php echo icon('x'); ?></div>
    </div>
    <div class="tile-value"><?php echo $adDismissed; ?></div>
    <div class="tile-sub">Of the last <?php echo count($history); ?> reviewed</div>
  </section>

  <div class="span-8 ad-stack">
  <?php if (empty($pendingDrafts)): ?>
    <section class="tile">
      <div class="empty-state">
        <div class="icon-button"><?php echo icon('mail'); ?></div>
        <p>No drafts waiting for review. The scheduled generator queues these automatically for leads that have gone quiet 14+ days — check back after it next runs, or trigger it manually if you're testing.</p>
      </div>
    </section>
  <?php else: foreach ($pendingDrafts as $d): ?>
    <section class="tile ad-draft">
      <div class="tile-head">
        <div>
          <div class="ad-company"><?php echo e($d['company_name']); ?></div>
          <div class="ad-meta">
            <span>Queued <?php echo date('j M Y', strtotime($d['created_at'])); ?></span>
            <?php if (!empty($d['officer_name'])): ?><span>· <?php echo e($d['officer_name']); ?></span><?php endif; ?>
            <?php if (!empty($d['contact_email'])): ?><span>· <?php echo e($d['contact_email']); ?></span><?php endif; ?>
          </div>
        </div>
        <span class="badge red">⚡ AI-generated — review before sending</span>
      </div>
      <form method="POST">
        <input type="hidden" name="draft_id" value="<?php echo (int) $d['id']; ?>">
        <div class="form-field">
          <label>Subject</label>
          <input type="text" name="subject" value="<?php echo e($d['subject']); ?>">
        </div>
        <div class="form-field">
          <label>Body (edit freely before sending)</label>
          <textarea name="body"><?php echo e($d['body']); ?></textarea>
        </div>
        <?php if (empty($d['contact_email'])): ?>
          <div class="ad-warn"><?php echo icon('alert'); ?><span>No contact email on file — add one on this lead, or if it's linked to a client, on the client's record, to enable direct sending.</span></div>
        <?php endif; ?>
        <div class="ad-foot">
          <div>
            <button type="submit" name="action" value="dismiss" class="btn-ghost"><?php echo icon('x'); ?> Dismiss</button>
          </div>
          <div class="right">
            <a class="btn-secondary" target="_blank"
               href="mailto:<?php echo e($d['contact_email'] ?? ''); ?>?subject=<?php echo rawurlencode($d['subject']); ?>&body=<?php echo rawurlencode($d['body']); ?>">
              <?php echo icon('mail'); ?> Open in Email App
            </a>
            <button type="submit" name="action" value="approve_send" class="btn-primary"><?php echo icon('send'); ?> Approve &amp; Send</button>
          </div>
        </div>
      </form>
    </section>
  <?php endforeach; endif; ?>
  </div>

  <div class="span-4 ad-stack ad-side">
    <section class="tile">
      <div class="tile-head"><h2 class="tile-title">Recent History</h2><span class="badge navy"><?php echo count($history); ?></span></div>
      <?php if (empty($history)): ?>
        <p class="tile-sub">Approved and dismissed drafts will appear here.</p>
      <?php else: foreach ($history as $h): ?>
        <div class="ad-hist">
          <span class="badge <?php echo $h['status'] === 'sent' ? 'stage-client' : 'stage-lost'; ?>" style="flex-shrink:0;"><?php echo e(ucfirst($h['status'])); ?></span>
          <div class="t">
            <b><?php echo e($h['company_name']); ?></b><?php echo e($h['subject']); ?>
            <div class="d"><?php echo $h['reviewed_at'] ? date('j M Y', strtotime($h['reviewed_at'])) : ''; ?></div>
          </div>
        </div>
      <?php endforeach; endif; ?>
    </section>
    <section class="tile tile--soft">
      <div class="tile-head"><h2 class="tile-title">How this queue works</h2></div>
      <ol class="ad-steps">
        <li><span class="n">1</span><span>A scheduled job drafts a follow-up for leads quiet for 14+ days.</span></li>
        <li><span class="n">2</span><span>You edit the subject and body — nothing is sent automatically.</span></li>
        <li><span class="n">3</span><span>Approve &amp; Send, or open it in your email app if server sending fails.</span></li>
      </ol>
    </section>
  </div>
</div>

<?php require_once __DIR__ . '/includes/footer.php'; ?>
