<?php
/**
 * IEMA CRMOps — User Management
 * -----------------------------------------------------------------------
 * IT Admin and Management are the two roles that provision logins for
 * everyone else — BD Officers and BD Managers do not self-register and
 * do not have access to this page. Both roles have equal reach: either
 * can create, suspend, reset, or reassign roles for any account,
 * including each other's.
 * -----------------------------------------------------------------------
 */
require_once __DIR__ . '/config.php';
require_login();

if (!role_is(['it_admin', 'management'])) {
    header('Location: dashboard.php');
    exit;
}

$role = current_role();
$uid  = (int) ($_SESSION['user_id'] ?? 0);

const CREATABLE_ROLES_BY_ROLE = [
    'it_admin'   => ['bd_officer', 'bd_manager', 'management', 'account_manager', 'it_admin', 'auditor'],
    'management' => ['bd_officer', 'bd_manager', 'management', 'account_manager', 'it_admin', 'auditor'],
];
$creatableRoles = CREATABLE_ROLES_BY_ROLE[$role];

$error   = '';
$success = '';

// ── Create user + assign credentials ─────────────────────────────────────
if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'create_user') {
    $name          = trim($_POST['name']     ?? '');
    $email         = trim($_POST['email']    ?? '');
    $newRole       = $_POST['role']          ?? '';
    $setPassword   = $_POST['password']      ?? '';
    $autoGenerated = false;

    if ($name === '' || !filter_var($email, FILTER_VALIDATE_EMAIL)) {
        $error = 'Please provide a valid name and email.';
    } elseif (!in_array($newRole, $creatableRoles, true)) {
        $error = 'You are not permitted to create a user with that role.';
    } elseif ($setPassword !== '' && strlen($setPassword) < 8) {
        $error = 'Password must be at least 8 characters — leave it blank to auto-generate one instead.';
    } else {
        $existing = $pdo->prepare('SELECT id FROM users WHERE email = ?');
        $existing->execute([$email]);
        if ($existing->fetch()) {
            $error = 'A user with that email already exists.';
        } else {
            if ($setPassword === '') {
                $setPassword   = bin2hex(random_bytes(5));
                $autoGenerated = true;
            }
            $hash = password_hash($setPassword, PASSWORD_BCRYPT);
            $stmt = $pdo->prepare('INSERT INTO users (name, email, password_hash, role, status) VALUES (?,?,?,?,"active")');
            $stmt->execute([$name, $email, $hash, $newRole]);
            $newId = (int) $pdo->lastInsertId();

            $audit = $pdo->prepare('INSERT INTO audit_log (user_id, action, entity_type, entity_id, details) VALUES (?,?,?,?,?)');
            $audit->execute([$uid, 'create', 'user', $newId, "Created user $email ({$newRole}) — credentials assigned by " . e(current_role_label())]);

            $success = ($autoGenerated ? 'User created with an auto-generated password: ' : 'User created with the password you assigned: ')
                . '<code>' . e($setPassword) . '</code> — share this with them securely and ask them to sign in and note it down.';
        }
    }
}

// ── Suspend / reactivate ──────────────────────────────────────────────────
if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'toggle_status') {
    $targetId   = (int) ($_POST['user_id'] ?? 0);
    $targetStmt = $pdo->prepare('SELECT role, status FROM users WHERE id = ?');
    $targetStmt->execute([$targetId]);
    $target = $targetStmt->fetch();

    if ($targetId === $uid) {
        $error = "You can't suspend your own account.";
    } elseif (!$target) {
        $error = 'User not found.';
    } elseif (!in_array($target['role'], $creatableRoles, true)) {
        $error = 'You are not permitted to manage a user with that role.';
    } else {
        $newStatus = $target['status'] === 'active' ? 'suspended' : 'active';
        $pdo->prepare('UPDATE users SET status = ? WHERE id = ?')->execute([$newStatus, $targetId]);

        $audit = $pdo->prepare('INSERT INTO audit_log (user_id, action, entity_type, entity_id, details) VALUES (?,?,?,?,?)');
        $audit->execute([$uid, 'update', 'user', $targetId, "Status changed to $newStatus"]);

        $success = 'User status updated.';
    }
}

// ── Change password (admin sets a specific new password) ──────────────────
if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'change_password') {
    $targetId    = (int) ($_POST['user_id']        ?? 0);
    $newPassword = trim($_POST['new_password']     ?? '');
    $confirmPass = trim($_POST['confirm_password'] ?? '');

    $targetStmt = $pdo->prepare('SELECT role, name FROM users WHERE id = ?');
    $targetStmt->execute([$targetId]);
    $target = $targetStmt->fetch();

    if (!$target || !in_array($target['role'], $creatableRoles, true)) {
        $error = 'You are not permitted to change the password for that user.';
    } elseif ($newPassword === '') {
        $error = 'Please enter a new password.';
    } elseif (strlen($newPassword) < 8) {
        $error = 'Password must be at least 8 characters.';
    } elseif ($newPassword !== $confirmPass) {
        $error = 'Passwords do not match — please try again.';
    } else {
        $hash = password_hash($newPassword, PASSWORD_BCRYPT);
        $pdo->prepare('UPDATE users SET password_hash = ? WHERE id = ?')->execute([$hash, $targetId]);

        $audit = $pdo->prepare('INSERT INTO audit_log (user_id, action, entity_type, entity_id, details) VALUES (?,?,?,?,?)');
        $audit->execute([$uid, 'update', 'user', $targetId, 'Password changed by ' . e(current_role_label())]);

        $success = 'Password updated for <strong>' . e($target['name']) . '</strong>. Share the new password with them securely.';
    }
}

// ── Change role ───────────────────────────────────────────────────────────
if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'change_role') {
    $targetId = (int) ($_POST['user_id'] ?? 0);
    $newRole  = $_POST['new_role']       ?? '';

    $targetStmt = $pdo->prepare('SELECT role, name FROM users WHERE id = ?');
    $targetStmt->execute([$targetId]);
    $target = $targetStmt->fetch();

    if ($targetId === $uid) {
        $error = "You can't change your own role.";
    } elseif (!$target) {
        $error = 'User not found.';
    } elseif (!in_array($target['role'], $creatableRoles, true)) {
        $error = 'You are not permitted to manage a user with that role.';
    } elseif (!in_array($newRole, $creatableRoles, true)) {
        $error = 'You are not permitted to assign that role.';
    } elseif ($newRole === $target['role']) {
        $error = 'User already has that role — no change made.';
    } else {
        $pdo->prepare('UPDATE users SET role = ? WHERE id = ?')->execute([$newRole, $targetId]);

        $audit = $pdo->prepare('INSERT INTO audit_log (user_id, action, entity_type, entity_id, details) VALUES (?,?,?,?,?)');
        $audit->execute([$uid, 'update', 'user', $targetId,
            "Role changed from {$target['role']} to {$newRole} by " . e(current_role_label())]);

        $success = 'Role updated for <strong>' . e($target['name']) . '</strong>.';
    }
}

$users      = $pdo->query('SELECT * FROM users ORDER BY created_at DESC')->fetchAll();
$roleLabels = ROLES;

require_once __DIR__ . '/includes/header.php';
?>

<?php
// Summary numbers — counted from the user list already loaded above.
$uActive    = count(array_filter($users, fn($x) => $x['status'] === 'active'));
$uSuspended = count($users) - $uActive;
$uNever     = count(array_filter($users, fn($x) => empty($x['last_login_at'])));
$uByRole    = [];
foreach ($users as $x) { $uByRole[$x['role']] = ($uByRole[$x['role']] ?? 0) + 1; }
?>
<style>
  /* ── Shared modal base ───────────────────────────────────────────────── */
  .modal-backdrop {
    display: none; position: fixed; inset: 0;
    background: rgba(11, 21, 36, 0.5); backdrop-filter: blur(4px);
    z-index: 100; align-items: center; justify-content: center; padding: 20px;
  }
  .modal-backdrop.open { display: flex; }

  .modal-box {
    background: #fff; border: 1px solid var(--line); border-radius: var(--r-tile); padding: 24px;
    width: 100%; max-width: 420px;
    box-shadow: var(--shadow-pop);
  }
  .modal-box h3 {
    font-family: 'Libre Franklin', sans-serif; font-size: 16px;
    margin: 0 0 4px 0;
  }
  .modal-subhead {
    font-size: 12.5px; color: var(--ink-500); margin-bottom: 20px;
  }

  /* ── Password strength ───────────────────────────────────────────────── */
  .pw-strength {
    height: 4px; border-radius: 2px; margin-top: 6px;
    background: var(--neutral-200); width: 100%; overflow: hidden;
  }
  .pw-strength-bar {
    height: 100%; border-radius: 2px; width: 0;
    transition: width .25s ease, background .25s ease;
  }
  .pw-hint { font-size: 11.5px; color: var(--ink-400); margin-top: 4px; min-height: 16px; }

  /* ── Role badge inside table ─────────────────────────────────────────── */
  .role-chip {
    display: inline-block; font-size: 11px; font-weight: 600;
    padding: 3px 9px; border-radius: 999px;
    background: #EEF2F8; color: var(--navy-700); white-space: nowrap;
  }
  .user-cell { display:flex; align-items:center; gap:10px; }
  .user-cell .avatar { width:32px; height:32px; font-size:11px; border-radius:9px; flex-shrink:0; }
  .user-cell .avatar.muted { background:var(--neutral-200); color:var(--ink-500); }
  .users-table .row-actions { flex-wrap:nowrap; }
  .users-table .row-actions form { display:inline; }
  .users-kpi { display:flex; align-items:flex-start; justify-content:space-between; gap:10px; }
  .role-stats .stat .v { font-size:22px; }
  .role-stats { grid-template-columns:repeat(6, minmax(0, 1fr)); }
  @media (max-width:1280px){ .role-stats { grid-template-columns:repeat(3, minmax(0, 1fr)); } }
  @media (max-width:560px){ .role-stats { grid-template-columns:repeat(2, minmax(0, 1fr)); } }
  .user-cell .row-name { white-space:nowrap; }
  .user-cell .row-sub { margin-top:1px; }
  #newUserForm { margin-bottom:0; }
  @media (max-width:760px){
    .table-wrap table.users-table { min-width:760px; }
  }
</style>

<div class="page-head">
  <div>
    <div class="eyebrow">Administration</div>
    <h1>User Accounts</h1>
    <p><?php echo e(current_role_label()); ?> assigns login credentials for CRMOps users — accounts aren't self-registered.</p>
  </div>
  <button class="btn-primary" onclick="openNewUserForm()">
    <?php echo icon('plus'); ?> Add User
  </button>
</div>

<?php if ($error): ?>
  <div class="alert error"><?php echo icon('alert'); ?><span><?php echo e($error); ?></span></div>
<?php endif; ?>
<?php if ($success): ?>
  <div class="alert success"><?php echo icon('check'); ?><span><?php echo $success; ?></span></div>
<?php endif; ?>

<div class="bento">
  <section class="tile tile--navy span-4">
    <div class="users-kpi">
      <div class="tile-label">Active users</div>
      <div class="tile-icon"><?php echo icon('users'); ?></div>
    </div>
    <div class="tile-value"><?php echo $uActive; ?></div>
    <div class="tile-sub"><?php echo count($users); ?> accounts · <?php echo $uSuspended; ?> suspended · <?php echo $uNever; ?> never signed in</div>
  </section>

  <section class="tile span-8">
    <div class="tile-head" style="margin-bottom:12px;">
      <h2 class="tile-title">Accounts by role</h2>
      <span class="tile-sub" style="margin:0;">Everyone who can sign in to CRMOps</span>
    </div>
    <div class="stat-row role-stats">
      <?php foreach ($roleLabels as $rk => $rl): ?>
        <div class="stat">
          <div class="v"><?php echo (int) ($uByRole[$rk] ?? 0); ?></div>
          <div class="l"><?php echo e($rl); ?></div>
        </div>
      <?php endforeach; ?>
    </div>
  </section>

  <!-- ── New user form ───────────────────────────────────────────────────── -->
  <div class="card-form span-12" id="newUserForm" style="display:none;">
    <div class="tile-head">
      <h2 class="tile-title"><?php echo icon('plus'); ?> New user</h2>
      <span class="tile-sub" style="margin:0;">Leave the password blank to auto-generate one.</span>
    </div>
    <form method="POST">
      <input type="hidden" name="action" value="create_user">
      <div class="form-grid" style="grid-template-columns:repeat(auto-fit, minmax(200px, 1fr));">
        <div class="form-field">
          <label>Full Name *</label>
          <input type="text" name="name" required>
        </div>
        <div class="form-field">
          <label>Email *</label>
          <input type="email" name="email" required>
        </div>
        <div class="form-field">
          <label>Role *</label>
          <select name="role" required>
            <?php foreach ($creatableRoles as $key): ?>
              <option value="<?php echo e($key); ?>"><?php echo e($roleLabels[$key]); ?></option>
            <?php endforeach; ?>
          </select>
        </div>
        <div class="form-field">
          <label>Initial Password</label>
          <input type="text" name="password" placeholder="Leave blank to auto-generate" minlength="8">
        </div>
      </div>
      <div class="form-actions">
        <button type="button" class="btn-secondary" onclick="closeNewUserForm()">Cancel</button>
        <button type="submit" class="btn-primary"><?php echo icon('check'); ?> Create User</button>
      </div>
    </form>
  </div>

  <!-- ── Users table ────────────────────────────────────────────────────── -->
  <section class="tile span-12">
    <div class="tile-head">
      <h2 class="tile-title">All accounts <span class="badge navy"><?php echo count($users); ?></span></h2>
      <span class="tile-sub" style="margin:0;">Newest first</span>
    </div>
    <div class="table-wrap">
      <table class="users-table">
        <thead>
          <tr>
            <th>User</th>
            <th>Role</th>
            <th>Status</th>
            <th>Last Login</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($users as $u):
            $manageable = in_array($u['role'], $creatableRoles, true) && (int) $u['id'] !== $uid;
            $initials = '';
            foreach (array_slice(preg_split('/\s+/', trim((string) $u['name'])), 0, 2) as $part) { $initials .= mb_strtoupper(mb_substr($part, 0, 1)); }
          ?>
          <tr>
            <td>
              <div class="user-cell">
                <span class="avatar<?php echo $u['status'] === 'active' ? '' : ' muted'; ?>"><?php echo e($initials); ?></span>
                <div>
                  <div class="row-name"><?php echo e($u['name']); ?></div>
                  <div class="row-sub"><?php echo e($u['email']); ?></div>
                </div>
              </div>
            </td>
            <td>
              <span class="role-chip">
                <?php echo e($roleLabels[$u['role']] ?? $u['role']); ?>
              </span>
            </td>
            <td>
              <span class="badge <?php echo $u['status'] === 'active' ? 'stage-client' : 'stage-lost'; ?>">
                <?php echo e(ucfirst($u['status'])); ?>
              </span>
            </td>
            <td style="white-space:nowrap;"><?php echo $u['last_login_at'] ? date('j M Y, g:ia', strtotime($u['last_login_at'])) : '<span class="row-sub">Never</span>'; ?></td>
            <td>
              <?php if ((int) $u['id'] === $uid): ?>
                <span class="badge navy">You</span>
              <?php elseif ($manageable): ?>
                <div class="row-actions">

                  <!-- Suspend / Reactivate -->
                  <form method="POST">
                    <input type="hidden" name="action"  value="toggle_status">
                    <input type="hidden" name="user_id" value="<?php echo (int) $u['id']; ?>">
                    <button type="submit"
                            class="<?php echo $u['status'] === 'active' ? 'btn-danger' : 'btn-secondary'; ?> btn-sm">
                      <?php echo $u['status'] === 'active' ? 'Suspend' : 'Reactivate'; ?>
                    </button>
                  </form>

                  <!-- Change Role -->
                  <button type="button" class="btn-secondary btn-sm"
                          onclick="openRoleModal(
                            <?php echo (int) $u['id']; ?>,
                            '<?php echo e(addslashes($u['name'])); ?>',
                            '<?php echo e($u['role']); ?>'
                          )">
                    Change Role
                  </button>

                  <!-- Change Password -->
                  <button type="button" class="btn-secondary btn-sm"
                          onclick="openPwModal(<?php echo (int) $u['id']; ?>, '<?php echo e(addslashes($u['name'])); ?>')">
                    Change Password
                  </button>

                </div>
              <?php else: ?>
                <span class="row-sub">—</span>
              <?php endif; ?>
            </td>
          </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    </div>
  </section>
</div>

<!-- ── Change-password modal ──────────────────────────────────────────── -->
<div class="modal-backdrop" id="pwModal">
  <div class="modal-box">
    <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:4px;">
      <h3>Change Password</h3>
      <button type="button" onclick="closePwModal()" class="btn-ghost" style="padding:4px 8px;">✕</button>
    </div>
    <div class="modal-subhead" id="pwModalFor"></div>

    <form method="POST" id="pwForm" onsubmit="return validatePwForm()">
      <input type="hidden" name="action"  value="change_password">
      <input type="hidden" name="user_id" id="pwUserId">

      <div class="form-field">
        <label>New Password</label>
        <input type="password" name="new_password" id="pwNew" required
               minlength="8" autocomplete="new-password"
               oninput="updateStrength(this.value)">
        <div class="pw-strength"><div class="pw-strength-bar" id="pwStrengthBar"></div></div>
        <div class="pw-hint" id="pwHint">At least 8 characters</div>
      </div>

      <div class="form-field" style="margin-top:14px;">
        <label>Confirm New Password</label>
        <input type="password" name="confirm_password" id="pwConfirm" required
               autocomplete="new-password"
               oninput="updatePwMatch()">
        <div class="pw-hint" id="pwMatchHint"></div>
      </div>

      <div class="form-actions" style="margin-top:20px;">
        <button type="button" class="btn-secondary" onclick="closePwModal()">Cancel</button>
        <button type="submit" class="btn-primary"><?php echo icon('check'); ?> Save Password</button>
      </div>
    </form>
  </div>
</div>

<!-- ── Change-role modal ──────────────────────────────────────────────── -->
<div class="modal-backdrop" id="roleModal">
  <div class="modal-box">
    <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:4px;">
      <h3>Change Role</h3>
      <button type="button" onclick="closeRoleModal()" class="btn-ghost" style="padding:4px 8px;">✕</button>
    </div>
    <div class="modal-subhead" id="roleModalFor"></div>

    <form method="POST">
      <input type="hidden" name="action"  value="change_role">
      <input type="hidden" name="user_id" id="roleUserId">

      <div class="form-field">
        <label>New Role</label>
        <select name="new_role" id="roleSelect" required>
          <?php foreach ($creatableRoles as $key): ?>
            <option value="<?php echo e($key); ?>"><?php echo e($roleLabels[$key]); ?></option>
          <?php endforeach; ?>
        </select>
      </div>

      <div class="form-actions" style="margin-top:20px;">
        <button type="button" class="btn-secondary" onclick="closeRoleModal()">Cancel</button>
        <button type="submit" class="btn-primary"><?php echo icon('check'); ?> Save Role</button>
      </div>
    </form>
  </div>
</div>

<script>
// ── New user form ─────────────────────────────────────────────────────────
function openNewUserForm() {
  document.getElementById('newUserForm').style.display = 'block';
  document.querySelector('.page-head .btn-primary').style.display = 'none';
}
function closeNewUserForm() {
  document.getElementById('newUserForm').style.display = 'none';
  document.querySelector('.page-head .btn-primary').style.display = '';
}

// ── Password modal ────────────────────────────────────────────────────────
function openPwModal(userId, userName) {
  document.getElementById('pwUserId').value         = userId;
  document.getElementById('pwModalFor').textContent = 'Setting a new password for ' + userName;
  document.getElementById('pwNew').value            = '';
  document.getElementById('pwConfirm').value        = '';
  document.getElementById('pwMatchHint').textContent = '';
  updateStrength('');
  document.getElementById('pwModal').classList.add('open');
  setTimeout(() => document.getElementById('pwNew').focus(), 80);
}
function closePwModal() {
  document.getElementById('pwModal').classList.remove('open');
}
document.getElementById('pwModal').addEventListener('click', function (e) {
  if (e.target === this) closePwModal();
});

// ── Role modal ────────────────────────────────────────────────────────────
function openRoleModal(userId, userName, currentRole) {
  document.getElementById('roleUserId').value         = userId;
  document.getElementById('roleModalFor').textContent = 'Changing role for ' + userName;
  document.getElementById('roleSelect').value         = currentRole;
  document.getElementById('roleModal').classList.add('open');
  setTimeout(() => document.getElementById('roleSelect').focus(), 80);
}
function closeRoleModal() {
  document.getElementById('roleModal').classList.remove('open');
}
document.getElementById('roleModal').addEventListener('click', function (e) {
  if (e.target === this) closeRoleModal();
});

// ── Password strength indicator ───────────────────────────────────────────
function updateStrength(val) {
  const bar  = document.getElementById('pwStrengthBar');
  const hint = document.getElementById('pwHint');
  let score  = 0;

  if (val.length >= 8)                               score++;
  if (val.length >= 12)                              score++;
  if (/[A-Z]/.test(val) && /[a-z]/.test(val))       score++;
  if (/[0-9]/.test(val))                             score++;
  if (/[^A-Za-z0-9]/.test(val))                     score++;

  const levels = [
    { pct: '0%',   bg: 'transparent',               label: 'At least 8 characters' },
    { pct: '25%',  bg: '#ef4444',                   label: 'Weak'   },
    { pct: '50%',  bg: '#f97316',                   label: 'Fair'   },
    { pct: '75%',  bg: '#eab308',                   label: 'Good'   },
    { pct: '100%', bg: 'var(--green-600,#16a34a)',  label: 'Strong' },
  ];

  const level = val.length === 0 ? levels[0] : levels[Math.min(score, 4)];
  bar.style.width      = level.pct;
  bar.style.background = level.bg;
  hint.textContent     = val.length === 0 ? 'At least 8 characters' : level.label;
  hint.style.color     = val.length === 0 ? 'var(--ink-400)' : level.bg;
}

// ── Live password match feedback ──────────────────────────────────────────
function updatePwMatch() {
  const hint  = document.getElementById('pwMatchHint');
  const val   = document.getElementById('pwConfirm').value;
  if (val === '') { hint.textContent = ''; return; }
  const match = val === document.getElementById('pwNew').value;
  hint.textContent = match ? '✓ Passwords match' : '✗ Passwords do not match';
  hint.style.color = match ? 'var(--green-600,#16a34a)' : '#ef4444';
}

// ── Client-side validation before password submit ─────────────────────────
function validatePwForm() {
  const pw      = document.getElementById('pwNew').value;
  const confirm = document.getElementById('pwConfirm').value;
  const hint    = document.getElementById('pwHint');
  const mHint   = document.getElementById('pwMatchHint');

  if (pw.length < 8) {
    hint.textContent = 'Password must be at least 8 characters.';
    hint.style.color = '#ef4444';
    document.getElementById('pwNew').focus();
    return false;
  }
  if (pw !== confirm) {
    mHint.textContent = '✗ Passwords do not match';
    mHint.style.color = '#ef4444';
    document.getElementById('pwConfirm').focus();
    return false;
  }
  return true;
}

// ── Auto-open new user form if ?new= is in URL ────────────────────────────
<?php if (isset($_GET['new'])): ?>
  openNewUserForm();
  document.getElementById('newUserForm').scrollIntoView({ behavior: 'smooth', block: 'start' });
<?php endif; ?>
</script>

<?php require_once __DIR__ . '/includes/footer.php'; ?>